// <auto-generated />
using System;
using BlueSkyChineseRestaurantPOS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BlueSkyChineseRestaurantPOS.Migrations
{
    [DbContext(typeof(PosDbContext))]
    [Migration("20260827073446_RenamedCustomizationAndAddedMenuItemModel")]
    partial class RenamedCustomizationAndAddedMenuItemModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BlueSkyChineseRestaurantPOS.Models.CustomerOrderItemCustomizationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerOrderItemId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Modification")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModificationChineseName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModificationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Option")
                        .HasColumnType("text");

                    b.Property<decimal>("PriceChange")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CustomerOrderItemId");

                    b.ToTable("OrderItemCustomizations");
                });

            modelBuilder.Entity("BlueSkyChineseRestaurantPOS.Models.CustomerOrderItemModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChineseItemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CustomerOrderId")
                        .HasColumnType("integer");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrderedAmount")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<bool>("ToGo")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CustomerOrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("BlueSkyChineseRestaurantPOS.Models.CustomerOrderModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("DiscountConstant")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("DiscountPercent")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("OrderTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Tax")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("BlueSkyChineseRestaurantPOS.Models.MenuItemModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ChineseItemName")
                        .HasColumnType("text");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrderedAmount")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<bool>("toGo")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("MenuItems");
                });

            modelBuilder.Entity("BlueSkyChineseRestaurantPOS.Models.CustomerOrderItemCustomizationModel", b =>
                {
                    b.HasOne("BlueSkyChineseRestaurantPOS.Models.CustomerOrderItemModel", "CustomerOrderItem")
                        .WithMany("MenuItemCustomizations")
                        .HasForeignKey("CustomerOrderItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerOrderItem");
                });

            modelBuilder.Entity("BlueSkyChineseRestaurantPOS.Models.CustomerOrderItemModel", b =>
                {
                    b.HasOne("BlueSkyChineseRestaurantPOS.Models.CustomerOrderModel", "CustomerOrder")
                        .WithMany("CustomerOrderItems")
                        .HasForeignKey("CustomerOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerOrder");
                });

            modelBuilder.Entity("BlueSkyChineseRestaurantPOS.Models.CustomerOrderItemModel", b =>
                {
                    b.Navigation("MenuItemCustomizations");
                });

            modelBuilder.Entity("BlueSkyChineseRestaurantPOS.Models.CustomerOrderModel", b =>
                {
                    b.Navigation("CustomerOrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
